pipeline {
  agent any
  stages {
    stage('Build Docker Image') {
      steps {
        script {
          docker.build("msd967/nginx:${env.BUILD_ID}")
        }
      }
    }
    stage('Push Docker Image to DockerHub') {
      steps {
        script {
          docker.withRegistry('https://registry.hub.docker.com', 'bb7a18e2-6369-4acf-9ffa-e4f88f91e164') {
            dockerImage.push()
          }
        }
      }
    }
  }
}
